pipeline {
  agent any
  options {
    buildDiscarder(logRotator(numToKeepStr: '5'))
  }
  triggers {
    cron('@daily')
  }
  stages {
    //Building Images from Dockerfile
    stage('Build') {
      steps {
        sh 'cd store-frontend-instrumented-fixed/'
        sh 'docker build -f "/ecommerce-workshop/store-frontend-instrumented-fixed/Dockerfile" -t andriyskyy/storedog:latest .'
      }
    }
    //Pushing images to public repository
    stage('Publish') {
      steps {
        withDockerRegistry([ credentialsId: "docker-hub", url: "" ]) {
          sh 'docker push andriyskyy/storedog:latest'
        }
      }
    }
  }
}
