name: Ads Service Test and Build

on:
  push:
    branches: [ master ]
    paths:
      - ads-service/**

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Container Registry Login
      env:
        MARTINISOFT_TOKEN: ${{ secrets.MARTINISOFT_TOKEN }}
      run: echo $MARTINISOFT_TOKEN | docker login docker.pkg.github.com -u martinisoft --password-stdin
    - name: Build the Ads Service
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/datadog/ecommerce-workshop/advertisements:latest
      working-directory: ./ads-service
    - name: Publish the Ads Service
      run: docker push docker.pkg.github.com/datadog/ecommerce-workshop/advertisements:latest
